### PR TITLE
Fixes type error while getting heading tags

### LINKED ISSUE #1202: TypeError: undefined is not an object (evaluating 'a.type')
Sentry Issue: [LII-41](https://lawsafrica.sentry.io/issues/4185611414/?referrer=github_integration)

```
TypeError: undefined is not an object (evaluating 'a.type')
  at None (/static/js/app-prod.6be2fd75213a.js:2:533333)
  at forEach ([native code])
  at f (/static/js/app-prod.6be2fd75213a.js:2:533121)
  at None (/static/js/app-prod.6be2fd75213a.js:2:684884)
  at None (/static/js/app-prod.6be2fd75213a.js:2:688283)
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by actlikewill**
- Fixes type error while generating TOC elements

fixes #1202

### CODE REVIEW

File: peachjam/js/utils/function.ts [hunk 1]
```diff
@@ -76,18 +76,20 @@ export function generateHtmlTocItems (content: HTMLElement): TOCItemType[] {
       }
       const top = stack[stack.length - 1];
 
-      if (top.type === heading.tagName) {
-        // siblings
-        if (stack.length > 1) {
-          stack[stack.length - 2].children.push(item);
+      if (top) {
```
Comment (actlikewill) [inline peachjam/js/utils/function.ts:79]: @nickmwangemi Just added this check to prevent the error when the toc is generated

**Review by nickmwangemi — APPROVED** [review]
